name: rickandmorty_app
description: Rick and Morty Flutter App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  http: ^1.1.0
  json_annotation: ^4.8.1
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  intl: ^0.18.1
  graphql: ^5.1.3
  path_provider: ^2.0.15
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  flutter_lints: ^1.0.0
  mocktail: ^0.3.0
  bloc_test: ^9.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/